### ISSUE TITLE
Invalid durationMs for current track

### ISSUE THREAD

**Issue by Jaja0624** [gilbarbara/react-spotify-web-playback#39] opened 2020-11-25 15:01 UTC
The durationMs for the track from the callback prop is the same as the track that was **previously** played. Thus, the first track durationMs will be correct, but all subsequent tracks will be incorrect.
From the callback prop
![image](https://user-images.githubusercontent.com/31715149/100245100-88f74c80-2eec-11eb-9b85-7af1db1902b7.png)

Actual
![image](https://user-images.githubusercontent.com/31715149/100245142-944a7800-2eec-11eb-8437-02b5064eec57.png)

**Comment by Jaja0624** [comment] 2020-11-25 15:03
wait sorry i just realized they have different ids..? Nvm ill see whats wrong with this...

**Comment by gilbarbara** [comment] 2020-11-30 03:11
I couldn't reproduce that.

When the player changes track the callback is being called twice in response to state changes from the web playback SDK. The second update is bringing the correct duration. On both calls, the artist and track are correct.
I can't say if it's a problem in this library or the SDK.
Can you reproduce it in the demo?

**Comment by gilbarbara** [comment] 2020-11-30 05:00
hey @Jaja0624 

So I changed the status update to wait for the complete information of the new track before calling the callback, so it should be fixed in the next version.

**Comment by Jaja0624** [comment] 2020-12-02 17:25
Thank you 👍

**Closed** 2020-12-03 22:03 UTC
Labels: bug, next release
